/**
 * Word-level timestamp — retained for backward compatibility with existing
 * article_audios.timing_data records that may contain words[].
 * No new code generates WordTimestamp values.
 */
export type WordTimestamp = {
  text: string;
  startTimeMs: number;
  endTimeMs: number;
};

export type SpokenBlock = {
  index: number;
  type: "title" | "excerpt" | "heading" | "paragraph" | "blockquote" | "caption" | "list_item";
  text: string;
  htmlTag?: string;
};

export type ParagraphTiming = {
  index: number;
  type: SpokenBlock["type"];
  text: string;
  startTimeMs: number;
  endTimeMs: number;
  /**
   * Optional — present in legacy database records generated with word-level sync.
   * Not generated by new audio synthesis. The player and renderer do not consume this.
   */
  words?: WordTimestamp[];
};

export type ArticleAudioTimingData = {
  durationMs: number;
  paragraphs: ParagraphTiming[];
  fullText: string;
  source?: "groq" | "estimated";
};

export type AudioGenerationStatus =
  | "not_generated"
  | "generating"
  | "ready"
  | "failed"
  | "stale";

export type ArticleAudioRecord = {
  id: string;
  article_id: string;
  content_hash: string;
  audio_url: string;
  storage_path: string;
  duration_seconds: number;
  voice: string;
  language: string;
  status: AudioGenerationStatus;
  timing_data: ArticleAudioTimingData;
  error_message?: string | null;
  created_at: string;
  updated_at: string;
};

export type AudioChunkSynthesisResult = {
  audioBuffer: Buffer;
  mimeType: string;
  durationMs: number;
};

